# Generated by Django 4.1.4 on 2023-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_problemset'),
        ('problems', '0001_problem'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problem_submissions', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='problemsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_submissions', to='submissions.submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problemset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problemset.problemset'),
        ),
    ]
