# Generated by Django 4.1.4 on 2023-07-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_related_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='problemsubmission',
            constraint=models.UniqueConstraint(fields=('submission', 'problem'), name='unique_submission_problem'),
        ),
    ]
