# Generated by Django 4.1.4 on 2023-04-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problemset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer_key',
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='problems.problem')),
            ],
        ),
    ]
