# Generated by Django 4.1.4 on 2023-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('problems', '0003_html_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
