# Generated by Django 4.1.4 on 2023-04-16 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemsetProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_origin', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problemset_mapping', to='problems.problem')),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_mapping', to='problemset.problemset')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(related_name='problemsets', through='problemset.ProblemsetProblem', to='problems.problem'),
        ),
        migrations.AddConstraint(
            model_name='problemsetproblem',
            constraint=models.UniqueConstraint(fields=('problemset', 'number'), name='unique_problemset_problem_number'),
        ),
        migrations.AddConstraint(
            model_name='problemsetproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_origin', True)), fields=('problem',), name='unique_problem_origin'),
        ),
    ]
