# Generated by Django 4.1.4 on 2023-07-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_problemset'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='problemsetproblem',
            constraint=models.UniqueConstraint(fields=('problemset', 'problem'), name='unique_problemset_problem'),
        ),
    ]
