# Generated by Django 4.1.4 on 2023-06-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tags', '0001_initial'), ('tags', '0002_rename_name_tag_label')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
